reverse move fixes and testing
marcbone/s_curve pull request #8
Opened 2022-12-19 15:48 UTC by r2k-in-the-vortex

Changes related to moving negative direction, including nonzero v0 and v1, testcases, more detailed example plots and codecov

![image](https://user-images.githubusercontent.com/30666740/208465281-e773604e-7c87-4f38-bedb-218f82458f32.png)

2023-01-15 15:22 UTC, marcbone requested changes
Sry that it took me so long. Your PR looks quite good, only minor things need to be changed.

2023-01-15 15:22 UTC, marcbone commented on README.md
> +[![codecov](https://codecov.io/github/r2k-in-the-vortex/s_curve/branch/main/graph/badge.svg?token=GF80SKI0TX)](https://codecov.io/github/r2k-in-the-vortex/s_curve)
This shouldnt point to your repo

2023-01-15 15:22 UTC, marcbone commented on src/lib.rs
> +    fn calc_times_case_2_precise(&self, mut _recursion_depth: i32) -> SCurveTimeIntervals {
why did you put an underscore in the parameter name? It is used

2023-01-15 15:22 UTC, marcbone commented on src/lib.rs
> +    // direction
make this a doc comment like above

2023-01-15 18:27 UTC, r2k-in-the-vortex commented on src/lib.rs
> +    // direction
Of course, let me know how you wish to resolve the other two questions and I'll put it all as a single commit.

2023-01-15 18:27 UTC, r2k-in-the-vortex commented on src/lib.rs
> +    fn calc_times_case_2_precise(&self, mut _recursion_depth: i32) -> SCurveTimeIntervals {
Because clippy said so and I figured it knows better than I do, if that's not the correct action, I can revert it
```
(base) r2k@DESKTOP-FT60JBF:~/testdir/s_curve$ cargo clippy
warning: parameter is only used in recursion
   --> src/lib.rs:284:45
    |
284 |     fn calc_times_case_2_precise(&self, mut recursion_depth: i32) -> SCurveTimeIntervals {
    |                                             ^^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_recursion_depth`
    |
note: parameter used here
   --> src/lib.rs:291:60
    |
291 |                 return new_input.calc_times_case_2_precise(recursion_depth);
    |                                                            ^^^^^^^^^^^^^^^
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#only_used_in_recursion
    = note: `#[warn(clippy::only_used_in_recursion)]` on by default

warning: `s_curve` (lib) generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
```

2023-01-15 18:27 UTC, r2k-in-the-vortex commented on README.md
> +[![codecov](https://codecov.io/github/r2k-in-the-vortex/s_curve/branch/main/graph/badge.svg?token=GF80SKI0TX)](https://codecov.io/github/r2k-in-the-vortex/s_curve)
Of course, I was hoping you would set up codecov for your repo and point it correctly. I found it useful to check which codepaths were tested and which were not. I can't of course set up codecov for repo that isn't mine, best I can do is delete this.

2023-01-16 18:29 UTC, marcbone commented on README.md
> +[![codecov](https://codecov.io/github/r2k-in-the-vortex/s_curve/branch/main/graph/badge.svg?token=GF80SKI0TX)](https://codecov.io/github/r2k-in-the-vortex/s_curve)
Ah ok I thought it would work out of the box. I set up the codecov. But I guess I need this [file](https://github.com/r2k-in-the-vortex/s_curve/blob/main/.github/actions-rs/grcov.yml) for it to work

2023-01-16 18:29 UTC, marcbone commented on src/lib.rs
> +    fn calc_times_case_2_precise(&self, mut _recursion_depth: i32) -> SCurveTimeIntervals {
You are right. Nvm

2023-01-16 18:48 UTC, r2k-in-the-vortex commented on README.md
> +[![codecov](https://codecov.io/github/r2k-in-the-vortex/s_curve/branch/main/graph/badge.svg?token=GF80SKI0TX)](https://codecov.io/github/r2k-in-the-vortex/s_curve)
Actually that file might be useless, that was my first try but I ended up adding it to [rust.yml](https://github.com/r2k-in-the-vortex/s_curve/blob/main/.github/workflows/rust.yml) Should have deleted the old file.

Lets see, if I commit deletion of that file and the doc comment and you have codecov set up right, then it should build and upload. Lets try.

2023-01-16 18:50 UTC, r2k-in-the-vortex commented on README.md
> +[![codecov](https://codecov.io/github/r2k-in-the-vortex/s_curve/branch/main/graph/badge.svg?token=GF80SKI0TX)](https://codecov.io/github/r2k-in-the-vortex/s_curve)
sry, nevermind, I have deleted that old file from r2k-in-the-vortex:reverse_move_updates branch

2023-01-16 19:24 UTC, r2k-in-the-vortex commented on README.md
> +[![codecov](https://codecov.io/github/r2k-in-the-vortex/s_curve/branch/main/graph/badge.svg?token=GF80SKI0TX)](https://codecov.io/github/r2k-in-the-vortex/s_curve)
Looks like it works, with bot and everything. The only thing left is to point it at the correct badge for your repo.

2023-02-05 20:55 UTC, merged